=== Moussa-Mikhail/car_dealer/src/main/resources/library.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="library.xsd" xmlns="library.xsd"
           elementFormDefault="qualified">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="books"/>
                <xs:element ref="members"/>
                <xs:element ref="employees"/>
                <xs:element ref="returnStatuses"/>
                <xs:element ref="checkouts"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="book" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="members">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="member" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="employee" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="returnStatuses">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="returnStatus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="checkouts">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="checkout" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="authorId" type="xs:integer"/>
                <xs:element name="genreId" type="xs:integer"/>
                <xs:element name="isbn" type="xs:string"/>
                <xs:element name="quantity" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="member">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="firstName" type="xs:string"/>
                <xs:element name="lastName" type="xs:string"/>
                <xs:element name="joinedDate" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="employee">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="firstName" type="xs:string"/>
                <xs:element name="lastName" type="xs:string"/>
                <xs:element name="salary" type="xs:integer"/>
                <xs:element name="hiredDate" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="returnStatus">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="description" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="checkout">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="memberId" type="xs:integer"/>
                <xs:element name="bookId" type="xs:integer"/>
                <xs:element name="employeeId" type="xs:integer"/>
                <xs:element name="returnStatusId" type="xs:integer"/>
                <xs:element name="checkoutDate" type="xs:date"/>
                <xs:element name="dueDate" type="xs:date"/>
                <xs:element name="returnedDate" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Moussa-Mikhail/car_dealer/src/main/resources/library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="library.xsd">
    <books>
        <book>
            <id>1</id>
            <title>Artemis Fowl</title>
            <authorId>1</authorId>
            <genreId>1</genreId>
            <isbn>978-1368036986</isbn>
            <quantity>4</quantity>
        </book>
        <book>
            <id>2</id>
            <title>Artemis Fowl: The Arctic Incident</title>
            <authorId>1</authorId>
            <genreId>1</genreId>
            <isbn>978-0-43945070-6</isbn>
            <quantity>3</quantity>
        </book>
    </books>
    <members>
        <member>
            <id>1</id>
            <firstName>Moussa</firstName>
            <lastName>Mikhail</lastName>
            <joinedDate>2023-01-20</joinedDate>
        </member>
        <member>
            <id>2</id>
            <firstName>John</firstName>
            <lastName>Doe</lastName>
            <joinedDate>2023-01-20</joinedDate>
        </member>
        <member>
            <id>3</id>
            <firstName>Alice</firstName>
            <lastName>Smith</lastName>
            <joinedDate>2023-01-20</joinedDate>
        </member>
        <member>
            <id>4</id>
            <firstName>Fake</firstName>
            <lastName>Person</lastName>
            <joinedDate>2023-01-20</joinedDate>
        </member>
    </members>
    <employees>
        <employee>
            <id>1</id>
            <firstName>John</firstName>
            <lastName>Doe</lastName>
            <salary>40000</salary>
            <hiredDate>2023-01-20</hiredDate>
        </employee>
        <employee>
            <id>2</id>
            <firstName>Alice</firstName>
            <lastName>Smith</lastName>
            <salary>40000</salary>
            <hiredDate>2023-01-20</hiredDate>
        </employee>
    </employees>
    <returnStatuses>
        <returnStatus>
            <id>1</id>
            <description>checked out</description>
        </returnStatus>
        <returnStatus>
            <id>2</id>
            <description>returned</description>
        </returnStatus>
        <returnStatus>
            <id>3</id>
            <description>late</description>
        </returnStatus>
    </returnStatuses>
    <checkouts>
        <checkout>
            <id>1</id>
            <memberId>1</memberId>
            <bookId>1</bookId>
            <employeeId>1</employeeId>
            <returnStatusId>1</returnStatusId>
            <checkoutDate>2023-01-20</checkoutDate>
            <dueDate>2023-01-20</dueDate>
            <returnedDate>2023-01-26</returnedDate>
        </checkout>
    </checkouts>
</library>
